spring:
  application:
    name: auth-service

  cloud:
    compatibility-verifier:
      enabled: false

server:
  servlet:
    context-path: /auth-service
  port: 8001

school:
  jwt:
    signer-key: 3de06d74dcee52b342cad1730c36b4ce32ad762b093e90b11617d8550bf79ea1
    access-token-validity-in-seconds: 900
    refresh-token-validity-in-seconds: 86400

logging:
  level:
    com.school.common_library.client.UserClient: DEBUG
