spring:
  application:
    name: auth-service

  cloud:
    compatibility-verifier:
      enabled: false

<<<<<<< HEAD
  datasource:
    url: jdbc:mysql://localhost:3306/users_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
#    password: youko2806
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
=======
>>>>>>> 75ddd60e06d84e8b139f6bda6a5ad24477274b51
server:
#  servlet:
#    context-path: /auth-service
  port: 8001

<<<<<<< HEAD
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
=======
school:
  jwt:
    signer-key: 3de06d74dcee52b342cad1730c36b4ce32ad762b093e90b11617d8550bf79ea1
    access-token-validity-in-seconds: 900
    refresh-token-validity-in-seconds: 86400
>>>>>>> 75ddd60e06d84e8b139f6bda6a5ad24477274b51

