spring:
  application:
    name: point-service

  datasource:
    url: jdbc:mysql://localhost:3306/point_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  #toi config gateway nên xóa này đi nhé
#  servlet:
#    context-path: /point-service
  port: 8091


logging:
  level:
    root: INFO
    com.example.point_service: DEBUG
    org.hibernate.SQL: DEBUG

student:
  service:
    url: http://localhost:8090
<<<<<<< HEAD
=======

school:
  jwt:
    signer-key: 3de06d74dcee52b342cad1730c36b4ce32ad762b093e90b11617d8550bf79ea1
    access-token-validity-in-seconds: 900
    refresh-token-validity-in-seconds: 86400
>>>>>>> 75ddd60e06d84e8b139f6bda6a5ad24477274b51
