
server:
  port: 8003
  servlet:
    context-path: /student-service

spring:
  application:
    name: student-service
  cloud:
    compatibility-verifier:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/students_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: youko2806
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true